### ISSUE TITLE
No telemetry sent after upgrading to rc.3

### ISSUE THREAD

**Issue by mikegoatly** [anastasiia-zolochevska/react-appinsights#67]
After upgrading from beta 5 to rc 3 I'm no longer seeing any telemetry sent, trace, event or page view. I suspect it's something to do with my configuration, but I can't see what I've done wrong.

I use a helper class for my logging, a cut down version being this:

``` typescript
import { ITelemetryItem, SeverityLevel, ApplicationInsights, IApplicationInsights } from '@microsoft/applicationinsights-web';
import { reactAI } from 'react-appinsights'
import { User } from 'oidc-client';

class PortalInsights {
    private isCompanyUser = "Undetermined"
    private ai : IApplicationInsights | null = null

    public initialize(history: any) {
        const { devenv, appInsightsId } = config;

        var appInsights = new ApplicationInsights({
            config: {
                instrumentationKey:appInsightsId, 
                extensions: [reactAI],
                extensionConfig: {
                    [reactAI.extensionId]: { 
                        history: history,
                        debug: devenv 
                    }
                }
            }
        });

        this.ai = appInsights.loadAppInsights();
        this.ai.addTelemetryInitializer(this.userTelemetryInitializer.bind(this))
    }

    public processProfile(user: User) {
        if (this.ai == null) {
            return;
        }

        const { profile: { email, sub: id } } = user;
        this.isCompanyUser = email.toLowerCase().endsWith("@company.com") ? "True" : "False";
        this.ai.setAuthenticatedUserContext(id.toString());
    }

    public trackEvent(eventName: TrackedEvent, data: {[key: string]: any}): void {
        if (this.ai == null) {
            return;
        }

        this.consoleLog(eventName, "#0044c4");
        this.ai.trackEvent({ name: eventName, properties: data })
    }

    private consoleLog(message: string, color: string) {
        if (config.devenv) {
            console.log(`%c ${message}`, `color: ${color};padding-left: 10px;border-left: 3px solid ${color}`)
        }
    }

    private userTelemetryInitializer(item: ITelemetryItem) {
        const data = item.baseData || [];
        item.baseData = data;

        const properties = data["properties"] || {};
        data["properties"] = properties;
        properties["IsCompanyUser"] = this.isCompanyUser;

        return true;
    }
```

Because I'm logging to the console in a dev environment I know that events/traces are getting pushed to the IApplicationInsights instance (i.e. it has been initialized and is not null).

I have checked that the app insights instrumentation key is being set correctly, so I'm at a loss as to why no telemetry is being sent.

**Comment by pviotti** [comment]
It all looks good... If you're sure the AppInsights instance has been initialized then there must be something else going on, like a network problem - but I guess you'd see it in the console too.  
Anyhow, I've published rc4, which supports the latest beta of AppInsights and contains a few minor changes (the API stays the same): see if it solves anything. Also, [here](https://github.com/Azure/react-appinsights/tree/typescript-rewrite#get-original-appinsights-object)'s another way of accessing the AppInsights instance. Apologies for the bumpy beta releases!

**Comment by mikegoatly** [comment]
Thanks for the quick response @pviotti - no worries on the bumpiness - if I had more time I'd get stuck in and debug it a bit more myself, so appreciate the support.

I've updated to rc4 and still have the same problem, with one additional one - the IApplicationInsights type returned from loadAppInsights() no longer has  setAuthenticatedUserContext on it (this is probably a change in the app insights JS library?)

I've tried using the appInsights property as you've suggested, but still no telemetry gets sent. It feels like the underlying app insights instance hasn't been hooked up properly, but inspecting the object in the browser shows it has been, and the correct instrumentation key is there.

I've tried stripping out everything apart from the basic `new ApplicationInsights` and `appInsights.loadAppInsights`, but even then, no luck.

**Comment by hiraldesai** [comment]
I can confirm this behavior myself. Let me dig deeper and see how this got broken. I'm also seeing the console logs till the very end, but not seeing any xhr posts to AI endpoints. Which basically means the queue isn't getting flushed. It could be an issue with the initialization code. I will contact with someone from AI team offline and post updates here.

**Comment by pviotti** [comment]
We published 3.0.0-rc.5, which should include a fix. @mikegoatly let us know in case you still experience this.

**Comment by mikegoatly** [comment]
@pviotti Confirmed fixed in rc.5 - thanks!

I'm still having trouble setting the authenticated user context though - as I mentioned before I suspect it's a change in the app insights library, but I can't immediately spot what I should be using, or find the relevant docs. Everything I've found so far still says to use setAuthenticatedUserContext, and that's not available any more. Have I missed something obvious?

**Comment by hiraldesai** [comment]
I noticed that too @mikegoatly and spoke to AI team about. But it is something that cannot be provided by the `reactAI.appInsights` object because what's available at the initialization of `ReactAI` is only a subset of the entire `ApplicationInsights`. The recommended way of setting user context is not to rely on reactAI at all, and instead use the variable initialized in the `index.tsx`. (`let appInsights = new ApplicationInsights({...`).

I'm not quite happy with the outcome because it basically tells the consumers that you have full `ApplicationInsights` object available at your disposal but doesn't really provide its full functionality. However, it looks like we might have to live with the limitation (and a caveat under readme) unless AI makes some changes in future to make it work.

**Comment by mikegoatly** [comment]
@hiraldesai Thanks - I've played around with it a bit and thought I could make it work like this:

``` typescript
var appInsights = new ApplicationInsights({
            config: {
                instrumentationKey:appInsightsId, 
                extensions: [reactAI],
                extensionConfig: {
                    [reactAI.extensionId]: { 
                        history: history,
                        debug: devenv 
                    }
                }
            }
        });

        appInsights.setAuthenticatedUserContext(...); // <--- you have access to the initialization object here
        this.ai = appInsights.loadAppInsights();
        this.ai.addTelemetryInitializer(this.userTelemetryInitializer.bind(this))
```

But I'm getting the error "Cannot read property 'user' of undefined".

It looks like [this is the failing line](https://github.com/Microsoft/ApplicationInsights-JS/blob/9c8def6dfff455d07810027f23b67881a9c856f3/vNext/AISKU/src/Initialization.ts#L196):

``` typescript
this.properties.context.user.setAuthenticatedUserContext(authenticatedUserId, accountId, storeInCookie);
```

Which would imply that the context hasn't been set up yet. I'll do a bit more digging, but it feels a bit chicken and egg; I can't set the context until it's been initialized, but once I have done I no longer can. 😕

**Comment by mikegoatly** [comment]
@hiraldesai Aha! Got it. You can still use the appInsights instance after initialization, so swapping these lines around makes it all work:

``` typescript
        this.ai = appInsights.loadAppInsights();
        appInsights.setAuthenticatedUserContext(...); // <--- you have access to the initialization object here
        this.ai.addTelemetryInitializer(this.userTelemetryInitializer.bind(this))
```

I think a lot of confusion has come for me from the renaming of the app insights Initialization type to ApplicationInsights - this is a bit misleading as it's not _actually_ the application insights object. If it was `ApplicationInsightsConfiguration`, `ApplicationInsightsInitializer` or `ApplicationInsightsBuilder` it would make more sense.

You first use the configuration object to configure app insights, create an instance and then go on to use it. It's a bit odd that you can subsequently go back to the configuration object to re-configure the created instance, but it makes a little more sense to me.

**Comment by hiraldesai** [comment]
I completely agree on the confusion part. In the hindsight - we'd not have exposed the original AI object from reactAI at all if we knew about this limitation. The recommended approach is to use the original AI object and hold on to it for use anywhere else in your app. This package will soon transition over to @microsoft/application-insights-web as a plugin and I will ensure that this property completely gets removed from the future version to avoid user confusion.

Closing this issue for now, I hope you found the answer you were looking for.

**Comment by Gaben007** [comment]
I've experienced same tracking issue with the latest 3.0.0-rc.6 version.
